[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dice = "6CYQopU5HkLcpdR8X3UQbhWj5QzRcPHat1VH62gFa6WK"

[programs.localnet]
dice = "6CYQopU5HkLcpdR8X3UQbhWj5QzRcPHat1VH62gFa6WK"

[programs.mainnet]
dice = "6CYQopU5HkLcpdR8X3UQbhWj5QzRcPHat1VH62gFa6WK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
